model_name: "convnext_tiny"
dataset:
  img_dir: "data/data_split"
  input_size: 224
  batch_size: 64
  num_workers: 8

train:
  epochs: 25
  learning_rate: 0.0001
  weight_decay: 0.05
  patience: 5
  device: "cuda"
  checkpoint_dir: "saved_models/convnext"
  results_dir: "src/results/convnext"