model_name: "efficientnet_b2"
dataset:
  img_dir: "data/data_split"
  input_size: 260
  batch_size: 64
  num_workers: 8

train:
  epochs: 30
  learning_rate: 0.0001
  weight_decay: 0.01
  patience: 7
  device: "cuda"
  checkpoint_dir: "checkpoints/efficientnet"
  results_dir: "src/results/efficientnet"
  use_class_weights: True